apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: smartlogix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: 582808359593.dkr.ecr.us-east-1.amazonaws.com/smartlogix-backend-ventas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas
  namespace: smartlogix
spec:
  type: ClusterIP
  selector:
    app: backend-ventas
  ports:
    - port: 8080
      targetPort: 8080